# Generated by Django 4.2.4 on 2023-08-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=1, max_length=150, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
